version: '3'

services:
  client:
    image: cowxing_client_dev
    container_name: cowxing_client_dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3999:3000'
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
