import { useEffect, useState } from "react";

import type { NextPage } from "next";
import Head from "next/head";
import styles from "styles/Home.module.scss";

import Navigation from "components/navigation/Navigation";

const Playground: NextPage = (props: any) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>client</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation />
            <h1>Playground</h1>
        </div>
    );
};

export default Playground;

//
