import { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
// import { ApolloClient, InMemoryCache, gql } from "@apollo/client";
import styles from "styles/Home.module.scss";
import Navigation from "components/navigation/Navigation";
import NavigationData from "components/navigation/NavigationData";


export async function getStaticProps() {
    return {
        props: {
            server: process.env.SERVER,
        },
    };
}

const MySQL: NextPage = (props: any) => {
    console.log("[Basics.tsx 20] props.server : ", props.server);
    const [data, setData] = useState<any[]>();

    useEffect(() => {
        async function getMySQLData() {
            try {
                const res = await fetch(`${props.server}/mysql`);
                const result = await res.json();
                setData(result.data[0].Tables_in_test1);
            } catch (error) {
                console.log("error");
            }
        }
        getMySQLData();
    }, [props.server]);

    return (
        <div className={styles.container}>
            <Head>
                <title>client</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation navLinks={NavigationData.links} />
            <h1>MySQL test</h1>
            <p>{data}</p>
        </div>
    );
};

export default MySQL;
