import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const About: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>cowxing template</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>About page</h1>
                <Link href="/playground/youtube_jack_herrington/ssr_and_ssg">
                    <a>/playground/youtube_jack_herrington/ssr_and_ssg</a>
                </Link>
            </main>
        </div>
    );
};

export default About;
