version: '3.4'

services:
  server:
    image: cowxing_server
    container_name: cowxing_server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '4301:4000'
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
