version: '3'

services:
  client:
    image: cowxing_server
    container_name: cowxing_server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4999:4000'
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
