import type { NextPage } from "next";
import Head from "next/head";

import Stack from "@mui/material/Stack";
import Button from "@mui/material/Button";

import Navigation from "components/navigation/Navigation";
import styles from "styles/Home.module.scss";

function handleClick(event: React.MouseEvent<HTMLDivElement, MouseEvent>) {
    event.preventDefault();
    console.info("You clicked a breadcrumb.");
}

const MaterialUI: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Material UI</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navigation />

            <Stack>
                <Button variant="text">Text</Button>
                <Button variant="contained">Contained</Button>
                <Button variant="outlined">Outlined</Button>
            </Stack>
        </div>
    );
};

export default MaterialUI;

//
