import type { NextPage } from "next";
import Head from "next/head";
import styles from "styles/Home.module.scss";
import Link from "next/link";

import Navigation from "components/navigation/Navigation";

/**
 * 2. SSR - server side rendering
 */
// export async function getServerSideProps() {}

/**
 * 3. SSG - static site generation
 */
// export async function getStaticProps() {}

const SSR_and_SSG: NextPage = () => {
    // console.log("VERSION:", process.env.VERSION);
    return (
        <div className={styles.container}>
            <Head>
                <title>cowxing template</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation />
            <ul>
                <li>
                    <p>CSR - client side rendering</p>
                    <Link href="/playground/youtube_jack_herrington/ssr_and_ssg/Example1/Example1">Example1</Link>
                </li>
                <li>
                    <p>SSR - server side rendering</p>
                    <Link href="/playground/youtube_jack_herrington/ssr_and_ssg/Example2/Example2">Example2</Link>
                </li>
                <li>
                    <p>SSG - server side generation</p>
                    <Link href="/playground/youtube_jack_herrington/ssr_and_ssg/Example3/Example3">Example3</Link>
                </li>
            </ul>
        </div>
    );
};

export default SSR_and_SSG;
